import * as api from "ts-resource-tastypie";
import * as weauth_models from "./weAuth";
import * as ong_models from "./ong";
import * as onu_models from "./onu";
import * as we_notify_models from "./weNotify";
import * as utils from "./utils";
export declare class Doador extends api.Tastypie.Model<Doador> {
    static resource: api.Tastypie.Resource<Doador>;
    nome: string;
    slug: string;
    is_avaliador: boolean;
    is_empresa: boolean;
    has_plugin: boolean;
    has_app: boolean;
    invite: string;
    foto: string;
    private _email;
    private _dt_updated;
    private _dt_created;
    private _we_notify;
    private _rede;
    private _ong_timeline;
    private _doacao_mes;
    private _user;
    private _check_slug_resource;
    private _doador_logado;
    private _set_all_notify_read;
    constructor(obj?: any);
    save(): Promise<Doador>;
    private initProfile;
    check_slug(slug: string): Promise<{
        available: boolean;
    }>;
    instalarPluginNavegador(navegador: string): Promise<any>;
    get email(): string;
    get dt_created(): string;
    get dt_updated(): string;
    get rede(): DoadorRede;
    get ong_timeline(): api.Tastypie.Resource<ong_models.OngTimeLine>;
    get doacao_mes(): api.Tastypie.Resource<DoadorDoacaoMes>;
    get we_notify(): api.Tastypie.Resource<we_notify_models.WeNotifyDoador>;
    get user(): weauth_models.User;
    get plugin_navegador(): utils.PluginNavegador;
    set_all_notify_read(): Promise<any>;
    notificarPlugin(): Promise<any>;
    getPontos(): Promise<DoadorPontos>;
    getDoacao(): Promise<DoadorDoacao>;
    getCompraAfiliadora(): Promise<DoadorCompraAfiliadoraStatus>;
    getAvaliador(): Promise<DoadorAvaliador>;
    getPluginNavegadorLog(): Promise<DoadorPluginNavegador>;
    getPreferencia(): Promise<DoadorPreferencia>;
    createAccount(name: string, email: string, password: string, kwargs?: any): Promise<Doador>;
    createAccountDoadorEmpresa(nome: string, email: string, cpf_cnpj: string, kwargs?: any): Promise<Doador>;
    login(username: string, password: string, kwargs?: any): Promise<Doador>;
    loginFacebook(username: string, facebook_uid: string, facebook_access_token: string, kwargs?: any): Promise<Doador>;
    quickLogin(auth?: {
        username: string;
        apikey: string;
    }, kwargs?: any): Promise<Doador>;
    reset_password_request(email: string, kwargs?: any): Promise<any>;
    reset_password_execute(token: string, password: string, kwargs?: any): Promise<Doador>;
    change_password(username: string, pass_old: string, pass_new: string, kwargs?: any): Promise<Doador>;
}
export declare class DoadorAvaliador extends api.Tastypie.Model<DoadorAvaliador> {
    static resource: api.Tastypie.Resource<DoadorAvaliador>;
    doador_id: number;
    acesso_ativo: boolean;
    cpf: string;
    rg: string;
    facebook: string;
    linkedin: string;
    cep: string;
    dt_updated: string;
    dt_created: string;
    constructor(obj?: any);
}
export declare class DoadorPluginNavegador extends api.Tastypie.Model<DoadorPluginNavegador> {
    static resource: api.Tastypie.Resource<DoadorPluginNavegador>;
    doador_id: number;
    navegador: string;
    dt_ultima_ativacao: string;
    dt_updated: string;
    dt_created: string;
    constructor(obj?: any);
}
export declare class DoadorPreferencia extends api.Tastypie.Model<DoadorPreferencia> {
    static resource: api.Tastypie.Resource<DoadorPreferencia>;
    doador_id: number;
    email_ao_ganhar_ponto: boolean;
    email_postagens_ong_pontuada: boolean;
    email_newsletter_welight: boolean;
    ong_pode_acessar_meu_email: boolean;
    constructor(obj?: any);
}
export declare class DoadorPontos extends api.Tastypie.Model<DoadorPontos> {
    static resource: api.Tastypie.Resource<DoadorPontos>;
    private _doador_id;
    private _recebidos;
    private _distribuidos;
    private _disponiveis;
    private _recebidos_cadastro;
    private _recebidos_convite;
    private _recebidos_compra;
    private _recebidos_plugin_installed;
    private _recebidos_app_installed;
    private _recebidos_perfil_completo;
    private _ong;
    private _distribuicao_resource;
    constructor(obj?: any);
    distribuir(ong_id: number, pontos: number): Promise<DoadorPontos>;
    get doador_id(): number;
    get recebidos(): number;
    get distribuidos(): number;
    get disponiveis(): number;
    get recebidos_cadastro(): number;
    get recebidos_convite(): number;
    get recebidos_compra(): number;
    get recebidos_plugin_installed(): number;
    get recebidos_app_installed(): number;
    get recebidos_perfil_completo(): number;
    get ong(): api.Tastypie.Resource<DoadorDoacaoOng>;
}
export declare class DoadorDoacaoMes extends api.Tastypie.Model<DoadorDoacaoMes> {
    static resource: api.Tastypie.Resource<DoadorDoacaoMes>;
    doador_id: number;
    mes: number;
    ano: number;
    moeda: string;
    doador_doacao_pendente: number;
    doador_doacao_direta: number;
    doador_doacao_pool: number;
    doador_doacao_total: number;
    doador_doacao_impacto: number;
    rede_acima_doacao_pendente: number;
    rede_acima_doacao_direta: number;
    rede_acima_doacao_pool: number;
    rede_acima_doacao_total: number;
    rede_abaixo_doacao_pendente: number;
    rede_abaixo_doacao_direta: number;
    rede_abaixo_doacao_pool: number;
    rede_abaixo_doacao_total: number;
    rede_direta_doacao_pendente: number;
    rede_direta_doacao_direta: number;
    rede_direta_doacao_pool: number;
    rede_direta_doacao_total: number;
    rede_indireta_doacao_pendente: number;
    rede_indireta_doacao_direta: number;
    rede_indireta_doacao_pool: number;
    rede_indireta_doacao_total: number;
    dt_created: string;
    constructor(obj?: any);
}
export declare class DoadorDoacao extends api.Tastypie.Model<DoadorDoacao> {
    static resource: api.Tastypie.Resource<DoadorDoacao>;
    private _doador_id;
    private _moeda;
    private _doador_doacao_pendente;
    private _doador_doacao_direta;
    private _doador_doacao_pool;
    private _doador_doacao_total;
    private _doador_doacao_soluz;
    private _doador_doacao_impacto;
    private _rede_acima_doacao_pendente;
    private _rede_acima_doacao_direta;
    private _rede_acima_doacao_pool;
    private _rede_acima_doacao_total;
    private _rede_abaixo_doacao_pendente;
    private _rede_abaixo_doacao_direta;
    private _rede_abaixo_doacao_pool;
    private _rede_abaixo_doacao_total;
    private _rede_direta_doacao_pendente;
    private _rede_direta_doacao_direta;
    private _rede_direta_doacao_pool;
    private _rede_direta_doacao_total;
    private _rede_indireta_doacao_pendente;
    private _rede_indireta_doacao_direta;
    private _rede_indireta_doacao_pool;
    private _rede_indireta_doacao_total;
    private _doacao_ong;
    private _doacao_ods;
    private _dt_updated;
    constructor(obj?: any);
    get moeda(): string;
    get doador_doacao_pendente(): number;
    get doador_doacao_direta(): number;
    get doador_doacao_pool(): number;
    get doador_doacao_total(): number;
    get doador_doacao_soluz(): number;
    get doador_doacao_impacto(): number;
    get rede_acima_doacao_pendente(): number;
    get rede_acima_doacao_direta(): number;
    get rede_acima_doacao_pool(): number;
    get rede_acima_doacao_total(): number;
    get rede_abaixo_doacao_pendente(): number;
    get rede_abaixo_doacao_direta(): number;
    get rede_abaixo_doacao_pool(): number;
    get rede_abaixo_doacao_total(): number;
    get rede_direta_doacao_pendente(): number;
    get rede_direta_doacao_direta(): number;
    get rede_direta_doacao_pool(): number;
    get rede_direta_doacao_total(): number;
    get rede_indireta_doacao_pendente(): number;
    get rede_indireta_doacao_direta(): number;
    get rede_indireta_doacao_pool(): number;
    get rede_indireta_doacao_total(): number;
    get doacao_ong(): api.Tastypie.Resource<DoadorDoacaoOng>;
    get doacao_ods(): api.Tastypie.Resource<DoadorDoacaoOds>;
    get dt_updated(): string;
}
export declare class DoadorRede {
    private _doador_id;
    private _acima_resource;
    private _abaixo_resource;
    private _direta_resource;
    private _indireta_resource;
    constructor(doador_id: number);
    get doador_id(): number;
    get acima(): api.Tastypie.Resource<DoadorRedeAmigos>;
    get abaixo(): api.Tastypie.Resource<DoadorRedeAmigos>;
    get direta(): api.Tastypie.Resource<DoadorRedeAmigos>;
    get indireta(): api.Tastypie.Resource<DoadorRedeAmigos>;
}
export declare class DoadorRedeAmigos extends api.Tastypie.Model<DoadorRedeAmigos> {
    static resource: api.Tastypie.Resource<DoadorRedeAmigos>;
    doador_id: number;
    doador_nome: number;
    doador_email: number;
    parent_id: number;
    parent_nome: number;
    parent_email: number;
    parent_ativo: boolean;
    parent_dt_created: string;
    constructor(obj?: any);
}
export declare class DoadorDoacaoOng extends api.Tastypie.Model<DoadorDoacaoOng> {
    static resource: api.Tastypie.Resource<DoadorDoacaoOng>;
    ong: ong_models.Ong;
    doador_id: number;
    moeda: string;
    doacao_direta: number;
    doacao_pool: number;
    doacao_total: number;
    pontos: number;
    dt_updated: string;
    private _doacao_ods;
    constructor(obj?: any);
    get doacao_ods(): api.Tastypie.Resource<DoadorDoacaoOds>;
}
export declare class DoadorDoacaoOds extends api.Tastypie.Model<DoadorDoacaoOds> {
    static resource: api.Tastypie.Resource<DoadorDoacaoOds>;
    ods: onu_models.Ods;
    doador_id: number;
    moeda: string;
    doacao_direta: number;
    doacao_pool: number;
    doacao_total: number;
    nivel: number;
    dt_updated: string;
    private _doacao_ong;
    constructor(obj?: any);
    get doacao_ong(): api.Tastypie.Resource<DoadorDoacaoOng>;
}
export declare class DoadorCompraAfiliadoraStatus extends api.Tastypie.Model<DoadorCompraAfiliadoraStatus> {
    static resource: api.Tastypie.Resource<DoadorCompraAfiliadoraStatus>;
    private _doador_id;
    private _ativo;
    private _compra_qtde;
    private _doacao_total;
    private _doacao_porcentagem;
    private _dt_updated;
    private _compra;
    constructor(obj?: any);
    get doador_id(): number;
    get ativo(): boolean;
    get compra_qtde(): number;
    get doacao_total(): number;
    get doacao_porcentagem(): number;
    get dt_updated(): string;
    get compra(): api.Tastypie.Resource<DoadorCompraAfiliadora>;
}
export declare class DoadorCompraAfiliadora extends api.Tastypie.Model<DoadorCompraAfiliadora> {
    static resource: api.Tastypie.Resource<DoadorCompraAfiliadora>;
    uid: string;
    doador_id: number;
    doador_email: string;
    afiliadora_id: number;
    afiliadora_nome: string;
    loja_id: number;
    loja_nome: string;
    compra_moeda: string;
    compra_valor: number;
    comissao_moeda: string;
    comissao_valor: number;
    cotacao_brl: number;
    comissao_valor_brl: number;
    doacao_porcentagem: number;
    taxas_afiliadora: number;
    total_taxa_adm: number;
    doacao_moeda: string;
    doacao_valor: number;
    status_compra: string;
    status_doacao: string;
    fatura_id: number;
    dt_compra: string;
    dt_aprovacao: string;
    dt_updated: string;
    dt_created: string;
    constructor(obj?: any);
}
